### ISSUE TITLE
YARP_MODULE_PATH warning with YARP version >= 3.0.0

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/icub-contrib-common#8]
Starting from `YARP 3.0.0`, `YARP_MODULE_PATH` is deprecated and the YARP CMake modules are automatically included. See [here](https://github.com/robotology/yarp/blob/d3fb843e513b637ebb79838e825d3fa60820adb4/cmake/template/YARPConfig.cmake.in#L260-L267).

As a consequence, if you use `ICUBcontrib` the following line spawns warning(s).
https://github.com/robotology/icub-contrib-common/blob/a64acb1e501944d326b0e8c21af06640a7b16a64/templates/ICUBcontribConfig.cmake.in#L8

My suggestion for backward compatibility is to check whether `YARP_VERSION_MAJOR LESS 3` and append `YARP_MODULE_PATH` or not.

**Comment by pattacini** [comment]
As discussed f2f, I'd better go for a full update in favor of YARP 3.0.0 without keeping backward compatibility.

Anyway, dealing with `YARP_MODULE_PATH` is still required somehow for finding `ACE` without YCM.
Will clean this up soon.

**Comment by claudiofantacci** [comment]
That's ok @pattacini, we can sort this out together as soon as we have some time 😄 .

**Comment by claudiofantacci** [comment]
Thanks!
